# 7. Exercícios
---
Vamos aplicar os conceitos que vimos em alguns exercícios.
Para isso, utilizaremos o dataset de preços de combustíveis no Brasil.

In [1]:
import pandas as pd

data = pd.read_csv("./datasets/GasPricesinBrazil_2004-2019 Pré Processado FINAL.csv", sep=',')
data

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133,5,2004
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115,5,2004
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098,5,2004
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,5,2004
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,1.400,0.240,0.066,0.941,0.077,0.7441,1.03170,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103387,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,3.499,3.690,0.818,0.018,2.756,0.000,2.7560,2.75600,0.000,6,2019
103388,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,3.230,3.789,0.950,0.038,2.451,0.402,1.9842,2.86610,0.164,6,2019
103389,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,2.699,3.499,0.914,0.065,1.998,0.000,1.9981,1.99810,0.000,6,2019
103390,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,2.699,3.490,0.646,0.076,2.374,0.165,2.0179,2.50930,0.070,6,2019
103391,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,3.689,3.699,1.179,0.001,2.518,0.000,2.5175,2.51750,0.000,6,2019

In [2]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103392 entries, 0 to 103391
Data columns (total 20 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   DATA INICIAL                   103392 non-null  object
 1   DATA FINAL                     103392 non-null  object
 2   REGIÃO                         103392 non-null  object
 3   ESTADO                         103392 non-null  object
 4   PRODUTO                        103392 non-null  object
 5   NÚMERO DE POSTOS PESQUISADOS   103392 non-null  int64
 6   UNIDADE DE MEDIDA              103392 non-null  object
 7   PREÇO MÉDIO REVENDA            103392 non-null  float64
 8   DESVIO PADRÃO REVENDA          103392 non-null  float64
 9   PREÇO MÍNIMO REVENDA           103392 non-null  float64
 10  PREÇO MÁXIMO REVENDA           103392 non-null  float64
 11  MARGEM MÉDIA REVENDA           103392 non-null  float64
 12  COEF DE VARIAÇÃO REVENDA       103392 non-null  float64
 13  PREÇO MÉDIO DISTRIBUIÇÃO       103392 non-null  float64
 14  DESVIO PADRÃO DISTRIBUIÇÃO     103392 non-null  float64
 15  PREÇO MÍNIMO DISTRIBUIÇÃO      103392 non-null  float64
 16  PREÇO MÁXIMO DISTRIBUIÇÃO      103392 non-null  float64
 17  COEF DE VARIAÇÃO DISTRIBUIÇÃO  103392 non-null  float64
 18  MÊS                            103392 non-null  int64
 19  ANO                            103392 non-null  int64
dtypes: float64(11), int64(3), object(6)
memory usage: 15.8+ MB


Como há apenas medições de janeiro a junho para o ano de 2019, resolvemos **remover** os dados deste ano da análise.

In [3]:
# Criando lista com índices que constam o ano como 2019
dados_2019 = list((data.query('ANO == 2019')).index)
dados_2019

# criando um novo dataframe com os índices de 2019 eliminados
df = data.drop(dados_2019)
df

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133,5,2004
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115,5,2004
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098,5,2004
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,5,2004
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,1.400,0.240,0.066,0.941,0.077,0.7441,1.03170,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99734,2018-12-30,2019-01-05,SUDESTE,RIO DE JANEIRO,GNV,122,R$/m3,3.080,0.262,2.798,3.999,0.699,0.085,2.381,0.161,2.1670,2.86970,0.068,12,2018
99735,2018-12-30,2019-01-05,NORDESTE,RIO GRANDE DO NORTE,GNV,10,R$/m3,3.465,0.060,3.370,3.590,0.759,0.017,2.706,0.000,2.7059,2.70590,0.000,12,2018
99736,2018-12-30,2019-01-05,SUL,RIO GRANDE DO SUL,GNV,16,R$/m3,3.402,0.103,3.199,3.499,1.296,0.030,2.106,0.249,1.8775,2.37240,0.118,12,2018
99737,2018-12-30,2019-01-05,SUL,SANTA CATARINA,GNV,15,R$/m3,2.944,0.124,2.790,3.199,0.670,0.042,2.274,0.283,1.8738,2.27400,0.124,12,2018
99738,2018-12-30,2019-01-05,SUDESTE,SAO PAULO,GNV,41,R$/m3,2.353,0.451,1.999,3.429,0.467,0.192,1.886,0.250,1.6400,2.33200,0.133,12,2018

In [4]:
# 2° maneira: filtragem, e não drop.
df = data.query("ANO != 2019")
df

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133,5,2004
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115,5,2004
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098,5,2004
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,5,2004
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,1.400,0.240,0.066,0.941,0.077,0.7441,1.03170,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99734,2018-12-30,2019-01-05,SUDESTE,RIO DE JANEIRO,GNV,122,R$/m3,3.080,0.262,2.798,3.999,0.699,0.085,2.381,0.161,2.1670,2.86970,0.068,12,2018
99735,2018-12-30,2019-01-05,NORDESTE,RIO GRANDE DO NORTE,GNV,10,R$/m3,3.465,0.060,3.370,3.590,0.759,0.017,2.706,0.000,2.7059,2.70590,0.000,12,2018
99736,2018-12-30,2019-01-05,SUL,RIO GRANDE DO SUL,GNV,16,R$/m3,3.402,0.103,3.199,3.499,1.296,0.030,2.106,0.249,1.8775,2.37240,0.118,12,2018
99737,2018-12-30,2019-01-05,SUL,SANTA CATARINA,GNV,15,R$/m3,2.944,0.124,2.790,3.199,0.670,0.042,2.274,0.283,1.8738,2.27400,0.124,12,2018
99738,2018-12-30,2019-01-05,SUDESTE,SAO PAULO,GNV,41,R$/m3,2.353,0.451,1.999,3.429,0.467,0.192,1.886,0.250,1.6400,2.33200,0.133,12,2018

Note que temos um novo dataframe com 99739 linhas, mas com índices fora desse intervalo.
Acontece que os registros mantiveram seus índices originais após a query.

Para resetar os índices de 0 a *num_linhas-1*, basta usarmos o método `.reset_index()`.

In [5]:
df.reset_index(drop=True, inplace=True)
df

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133,5,2004
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115,5,2004
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098,5,2004
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,5,2004
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,1.400,0.240,0.066,0.941,0.077,0.7441,1.03170,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99734,2018-12-30,2019-01-05,SUDESTE,RIO DE JANEIRO,GNV,122,R$/m3,3.080,0.262,2.798,3.999,0.699,0.085,2.381,0.161,2.1670,2.86970,0.068,12,2018
99735,2018-12-30,2019-01-05,NORDESTE,RIO GRANDE DO NORTE,GNV,10,R$/m3,3.465,0.060,3.370,3.590,0.759,0.017,2.706,0.000,2.7059,2.70590,0.000,12,2018
99736,2018-12-30,2019-01-05,SUL,RIO GRANDE DO SUL,GNV,16,R$/m3,3.402,0.103,3.199,3.499,1.296,0.030,2.106,0.249,1.8775,2.37240,0.118,12,2018
99737,2018-12-30,2019-01-05,SUL,SANTA CATARINA,GNV,15,R$/m3,2.944,0.124,2.790,3.199,0.670,0.042,2.274,0.283,1.8738,2.27400,0.124,12,2018
99738,2018-12-30,2019-01-05,SUDESTE,SAO PAULO,GNV,41,R$/m3,2.353,0.451,1.999,3.429,0.467,0.192,1.886,0.250,1.6400,2.33200,0.133,12,2018

Os índices agora foram **resetados**. Porém, os índices antigos se transformaram em *uma nova coluna* chamada 'index'.
Para removê-la durante o *reset*, basta passarmos o argumento `drop=True`.

## 7.1 (exercício diferente) Qual a quantidade de cada produto em cada região?

In [6]:
grupo = df.groupby(['PRODUTO', 'REGIÃO'])
resultado = grupo['REGIÃO'].value_counts().to_frame()
resultado

                               count
PRODUTO          REGIÃO
ETANOL HIDRATADO CENTRO OESTE   3022
                 NORDESTE       6821
                 NORTE          5021
                 SUDESTE        3039
                 SUL            2278
GASOLINA COMUM   CENTRO OESTE   3034
                 NORDESTE       6838
                 NORTE          5289
                 SUDESTE        3040
                 SUL            2279
GLP              CENTRO OESTE   2998
                 NORDESTE       6185
                 NORTE          5152
                 SUDESTE        3037
                 SUL            2268
GNV              CENTRO OESTE    825
                 NORDESTE       5030
                 NORTE           233
                 SUDESTE        2772
                 SUL            1847
ÓLEO DIESEL      CENTRO OESTE   3034
                 NORDESTE       6836
                 NORTE          5290
                 SUDESTE        3040
                 SUL            2279
ÓLEO DIESEL S10  CENTRO OESTE   1110
                 NORDESTE       2807
                 NORTE          2149
                 SUDESTE        1249
                 SUL             937

## 7.1 Qual a proporção de postos pesquisados para cada combustível em cada região?

Nota: tenho que calcular a quantidade de postos pesquisados para cada combustível em cada região.

In [7]:
grupo = df.groupby(['PRODUTO', 'REGIÃO'])
grupo.groups

{('ETANOL HIDRATADO', 'CENTRO OESTE'): [0, 1, 2, 3, 27, 28, 29, 30, 54, 55, 56, 57, 81, 82, 83, 84, 108, 109, 110, 111, 135, 136, 137, 138, 162, 163, 164, 165, 189, 190, 191, 192, 216, 217, 218, 219, 243, 244, 245, 246, 270, 271, 272, 273, 297, 298, 299, 300, 324, 325, 326, 327, 351, 352, 353, 354, 378, 379, 380, 381, 405, 406, 407, 408, 432, 433, 434, 435, 459, 460, 461, 462, 486, 487, 488, 489, 513, 514, 515, 516, 540, 541, 542, 543, 567, 568, 569, 570, 594, 595, 596, 597, 621, 622, 623, 624, 648, 649, 650, 651, ...], ('ETANOL HIDRATADO', 'NORDESTE'): [4, 5, 6, 7, 8, 9, 10, 11, 12, 31, 32, 33, 34, 35, 36, 37, 38, 39, 58, 59, 60, 61, 62, 63, 64, 65, 66, 85, 86, 87, 88, 89, 90, 91, 92, 93, 112, 113, 114, 115, 116, 117, 118, 119, 120, 139, 140, 141, 142, 143, 144, 145, 146, 147, 166, 167, 168, 169, 170, 171, 172, 173, 174, 193, 194, 195, 196, 197, 198, 199, 200, 201, 220, 221, 222, 223, 224, 225, 226, 227, 228, 247, 248, 249, 250, 251, 252, 253, 254, 255, 274, 275, 276, 277, 278, 279, 280, 281, 282, 301, ...], ('ETANOL HIDRATADO', 'NORTE'): [13, 14, 15, 16, 17, 18, 19, 40, 41, 42, 43, 44, 45, 46, 67, 68, 69, 70, 71, 72, 73, 94, 95, 96, 97, 98, 99, 100, 121, 122, 123, 124, 125, 126, 127, 148, 149, 150, 151, 152, 153, 154, 175, 176, 177, 178, 179, 180, 181, 202, 203, 204, 205, 206, 207, 208, 229, 230, 231, 232, 233, 234, 235, 256, 257, 258, 259, 260, 261, 262, 283, 284, 285, 286, 287, 288, 289, 310, 311, 312, 313, 314, 315, 316, 337, 338, 339, 340, 341, 342, 343, 364, 365, 366, 367, 368, 369, 370, 391, 392, ...], ('ETANOL HIDRATADO', 'SUDESTE'): [20, 21, 22, 23, 47, 48, 49, 50, 74, 75, 76, 77, 101, 102, 103, 104, 128, 129, 130, 131, 155, 156, 157, 158, 182, 183, 184, 185, 209, 210, 211, 212, 236, 237, 238, 239, 263, 264, 265, 266, 290, 291, 292, 293, 317, 318, 319, 320, 344, 345, 346, 347, 371, 372, 373, 374, 398, 399, 400, 401, 425, 426, 427, 428, 452, 453, 454, 455, 479, 480, 481, 482, 506, 507, 508, 509, 533, 534, 535, 536, 560, 561, 562, 563, 587, 588, 589, 590, 614, 615, 616, 617, 641, 642, 643, 644, 668, 669, 670, 671, ...], ('ETANOL HIDRATADO', 'SUL'): [24, 25, 26, 51, 52, 53, 78, 79, 80, 105, 106, 107, 132, 133, 134, 159, 160, 161, 186, 187, 188, 213, 214, 215, 240, 241, 242, 267, 268, 269, 294, 295, 296, 321, 322, 323, 348, 349, 350, 375, 376, 377, 402, 403, 404, 429, 430, 431, 456, 457, 458, 483, 484, 485, 510, 511, 512, 537, 538, 539, 564, 565, 566, 591, 592, 593, 618, 619, 620, 645, 646, 647, 672, 673, 674, 699, 700, 701, 726, 727, 728, 753, 754, 755, 780, 781, 782, 807, 808, 809, 834, 835, 836, 861, 862, 863, 888, 889, 890, 915, ...], ('GASOLINA COMUM', 'CENTRO OESTE'): [11980, 11981, 11982, 11983, 12007, 12008, 12009, 12010, 12034, 12035, 12036, 12037, 12061, 12062, 12063, 12064, 12088, 12089, 12090, 12091, 12115, 12116, 12117, 12118, 12142, 12143, 12144, 12145, 12169, 12170, 12171, 12172, 12196, 12197, 12198, 12199, 12223, 12224, 12225, 12226, 12250, 12251, 12252, 12253, 12277, 12278, 12279, 12280, 12304, 12305, 12306, 12307, 12331, 12332, 12333, 12334, 12358, 12359, 12360, 12361, 12385, 12386, 12387, 12388, 12412, 12413, 12414, 12415, 12439, 12440, 12441, 12442, 12466, 12467, 12468, 12469, 12493, 12494, 12495, 12496, 12520, 12521, 12522, 12523, 12547, 12548, 12549, 12550, 12574, 12575, 12576, 12577, 12601, 12602, 12603, 12604, 12628, 12629, 12630, 12631, ...], ('GASOLINA COMUM', 'NORDESTE'): [11984, 11985, 11986, 11987, 11988, 11989, 11990, 11991, 11992, 12011, 12012, 12013, 12014, 12015, 12016, 12017, 12018, 12019, 12038, 12039, 12040, 12041, 12042, 12043, 12044, 12045, 12046, 12065, 12066, 12067, 12068, 12069, 12070, 12071, 12072, 12073, 12092, 12093, 12094, 12095, 12096, 12097, 12098, 12099, 12100, 12119, 12120, 12121, 12122, 12123, 12124, 12125, 12126, 12127, 12146, 12147, 12148, 12149, 12150, 12151, 12152, 12153, 12154, 12173, 12174, 12175, 12176, 12177, 12178, 12179, 12180, 12181, 12200, 12201, 12202, 12203, 12204, 12205, 12206, 12207, 12208, 12227, 12228, 12229, 12230, 12231, 12232, 12233, 12234, 12235, 12254, 12255, 12256, 12257, 12258, 12259, 12260, 12261, 12262, 12281, ...], ('GASOLINA COMUM', 'NORTE'): [11993, 11994, 11995, 11996, 11997, 11998, 11999, 12020, 12021, 12022, 12023, 12024, 12025, 12026, 12047, 12048, 12049, 12050, 12051, 12052, 12053, 12074, 12075, 12076, 12077, 12078, 12079, 12080, 12101, 12102, 12103, 12104, 12105, 12106, 12107, 12128, 12129, 12130, 12131, 12132, 12133, 12134, 12155, 12156, 12157, 12158, 12159, 12160, 12161, 12182, 12183, 12184, 12185, 12186, 12187, 12188, 12209, 12210, 12211, 12212, 12213, 12214, 12215, 12236, 12237, 12238, 12239, 12240, 12241, 12242, 12263, 12264, 12265, 12266, 12267, 12268, 12269, 12290, 12291, 12292, 12293, 12294, 12295, 12296, 12317, 12318, 12319, 12320, 12321, 12322, 12323, 12344, 12345, 12346, 12347, 12348, 12349, 12350, 12371, 12372, ...], ('GASOLINA COMUM', 'SUDESTE'): [12000, 12001, 12002, 12003, 12027, 12028, 12029, 12030, 12054, 12055, 12056, 12057, 12081, 12082, 12083, 12084, 12108, 12109, 12110, 12111, 12135, 12136, 12137, 12138, 12162, 12163, 12164, 12165, 12189, 12190, 12191, 12192, 12216, 12217, 12218, 12219, 12243, 12244, 12245, 12246, 12270, 12271, 12272, 12273, 12297, 12298, 12299, 12300, 12324, 12325, 12326, 12327, 12351, 12352, 12353, 12354, 12378, 12379, 12380, 12381, 12405, 12406, 12407, 12408, 12432, 12433, 12434, 12435, 12459, 12460, 12461, 12462, 12486, 12487, 12488, 12489, 12513, 12514, 12515, 12516, 12540, 12541, 12542, 12543, 12567, 12568, 12569, 12570, 12594, 12595, 12596, 12597, 12621, 12622, 12623, 12624, 12648, 12649, 12650, 12651, ...], ('GASOLINA COMUM', 'SUL'): [12004, 12005, 12006, 12031, 12032, 12033, 12058, 12059, 12060, 12085, 12086, 12087, 12112, 12113, 12114, 12139, 12140, 12141, 12166, 12167, 12168, 12193, 12194, 12195, 12220, 12221, 12222, 12247, 12248, 12249, 12274, 12275, 12276, 12301, 12302, 12303, 12328, 12329, 12330, 12355, 12356, 12357, 12382, 12383, 12384, 12409, 12410, 12411, 12436, 12437, 12438, 12463, 12464, 12465, 12490, 12491, 12492, 12517, 12518, 12519, 12544, 12545, 12546, 12571, 12572, 12573, 12598, 12599, 12600, 12625, 12626, 12627, 12652, 12653, 12654, 12679, 12680, 12681, 12706, 12707, 12708, 12733, 12734, 12735, 12760, 12761, 12762, 12787, 12788, 12789, 12814, 12815, 12816, 12841, 12842, 12843, 12868, 12869, 12870, 12895, ...], ('GLP', 'CENTRO OESTE'): [24019, 24020, 24021, 24022, 24046, 24047, 24048, 24049, 24073, 24074, 24075, 24076, 24100, 24101, 24102, 24103, 24127, 24128, 24129, 24130, 24154, 24155, 24156, 24157, 24181, 24182, 24183, 24184, 24208, 24209, 24210, 24211, 24235, 24236, 24237, 24238, 24262, 24263, 24264, 24265, 24289, 24290, 24291, 24292, 24316, 24317, 24318, 24319, 24343, 24344, 24345, 24346, 24370, 24371, 24372, 24373, 24397, 24398, 24399, 24400, 24424, 24425, 24426, 24427, 24451, 24452, 24453, 24454, 24478, 24479, 24480, 24481, 24505, 24506, 24507, 24508, 24532, 24533, 24534, 24535, 24558, 24559, 24560, 24561, 24585, 24586, 24587, 24588, 24612, 24613, 24614, 24615, 24639, 24640, 24641, 24642, 24666, 24667, 24668, 24669, ...], ('GLP', 'NORDESTE'): [24023, 24024, 24025, 24026, 24027, 24028, 24029, 24030, 24031, 24050, 24051, 24052, 24053, 24054, 24055, 24056, 24057, 24058, 24077, 24078, 24079, 24080, 24081, 24082, 24083, 24084, 24085, 24104, 24105, 24106, 24107, 24108, 24109, 24110, 24111, 24112, 24131, 24132, 24133, 24134, 24135, 24136, 24137, 24138, 24139, 24158, 24159, 24160, 24161, 24162, 24163, 24164, 24165, 24166, 24185, 24186, 24187, 24188, 24189, 24190, 24191, 24192, 24193, 24212, 24213, 24214, 24215, 24216, 24217, 24218, 24219, 24220, 24239, 24240, 24241, 24242, 24243, 24244, 24245, 24246, 24247, 24266, 24267, 24268, 24269, 24270, 24271, 24272, 24273, 24274, 24293, 24294, 24295, 24296, 24297, 24298, 24299, 24300, 24301, 24320, ...], ('GLP', 'NORTE'): [24032, 24033, 24034, 24035, 24036, 24037, 24038, 24059, 24060, 24061, 24062, 24063, 24064, 24065, 24086, 24087, 24088, 24089, 24090, 24091, 24092, 24113, 24114, 24115, 24116, 24117, 24118, 24119, 24140, 24141, 24142, 24143, 24144, 24145, 24146, 24167, 24168, 24169, 24170, 24171, 24172, 24173, 24194, 24195, 24196, 24197, 24198, 24199, 24200, 24221, 24222, 24223, 24224, 24225, 24226, 24227, 24248, 24249, 24250, 24251, 24252, 24253, 24254, 24275, 24276, 24277, 24278, 24279, 24280, 24281, 24302, 24303, 24304, 24305, 24306, 24307, 24308, 24329, 24330, 24331, 24332, 24333, 24334, 24335, 24356, 24357, 24358, 24359, 24360, 24361, 24362, 24383, 24384, 24385, 24386, 24387, 24388, 24389, 24410, 24411, ...], ('GLP', 'SUDESTE'): [24039, 24040, 24041, 24042, 24066, 24067, 24068, 24069, 24093, 24094, 24095, 24096, 24120, 24121, 24122, 24123, 24147, 24148, 24149, 24150, 24174, 24175, 24176, 24177, 24201, 24202, 24203, 24204, 24228, 24229, 24230, 24231, 24255, 24256, 24257, 24258, 24282, 24283, 24284, 24285, 24309, 24310, 24311, 24312, 24336, 24337, 24338, 24339, 24363, 24364, 24365, 24366, 24390, 24391, 24392, 24393, 24417, 24418, 24419, 24420, 24444, 24445, 24446, 24447, 24471, 24472, 24473, 24474, 24498, 24499, 24500, 24501, 24525, 24526, 24527, 24528, 24551, 24552, 24553, 24554, 24578, 24579, 24580, 24581, 24605, 24606, 24607, 24608, 24632, 24633, 24634, 24635, 24659, 24660, 24661, 24662, 24686, 24687, 24688, 24689, ...], ('GLP', 'SUL'): [24043, 24044, 24045, 24070, 24071, 24072, 24097, 24098, 24099, 24124, 24125, 24126, 24151, 24152, 24153, 24178, 24179, 24180, 24205, 24206, 24207, 24232, 24233, 24234, 24259, 24260, 24261, 24286, 24287, 24288, 24313, 24314, 24315, 24340, 24341, 24342, 24367, 24368, 24369, 24394, 24395, 24396, 24421, 24422, 24423, 24448, 24449, 24450, 24475, 24476, 24477, 24502, 24503, 24504, 24529, 24530, 24531, 24555, 24556, 24557, 24582, 24583, 24584, 24609, 24610, 24611, 24636, 24637, 24638, 24663, 24664, 24665, 24690, 24691, 24692, 24716, 24717, 24718, 24743, 24744, 24745, 24770, 24771, 24772, 24797, 24798, 24799, 24824, 24825, 24826, 24851, 24852, 24853, 24878, 24879, 24880, 24905, 24906, 24907, 24932, ...], ('GNV', 'CENTRO OESTE'): [35892, 35907, 35922, 35937, 35952, 35967, 35982, 35997, 36012, 36027, 36042, 36057, 36072, 36087, 36102, 36117, 36132, 36147, 36162, 36177, 36192, 36207, 36222, 36237, 36252, 36267, 36283, 36298, 36313, 36329, 36345, 36360, 36375, 36390, 36405, 36420, 36436, 36451, 36466, 36481, 36495, 36510, 36525, 36541, 36557, 36572, 36588, 36604, 36620, 36635, 36650, 36665, 36680, 36695, 36710, 36725, 36740, 36755, 36770, 36785, 36800, 36815, 36830, 36845, 36860, 36875, 36890, 36918, 36932, 36948, 36962, 36991, 37006, 37021, 37037, 37053, 37068, 37084, 37100, 37116, 37132, 37148, 37164, 37180, 37196, 37212, 37228, 37244, 37259, 37275, 37291, 37307, 37323, 37339, 37355, 37371, 37387, 37403, 37419, 37435, ...], ('GNV', 'NORDESTE'): [35893, 35894, 35895, 35896, 35897, 35898, 35899, 35908, 35909, 35910, 35911, 35912, 35913, 35914, 35923, 35924, 35925, 35926, 35927, 35928, 35929, 35938, 35939, 35940, 35941, 35942, 35943, 35944, 35953, 35954, 35955, 35956, 35957, 35958, 35959, 35968, 35969, 35970, 35971, 35972, 35973, 35974, 35983, 35984, 35985, 35986, 35987, 35988, 35989, 35998, 35999, 36000, 36001, 36002, 36003, 36004, 36013, 36014, 36015, 36016, 36017, 36018, 36019, 36028, 36029, 36030, 36031, 36032, 36033, 36034, 36043, 36044, 36045, 36046, 36047, 36048, 36049, 36058, 36059, 36060, 36061, 36062, 36063, 36064, 36073, 36074, 36075, 36076, 36077, 36078, 36079, 36088, 36089, 36090, 36091, 36092, 36093, 36094, 36103, 36104, ...], ('GNV', 'NORTE'): [36940, 37029, 37045, 37076, 37092, 37108, 37124, 37140, 37156, 37172, 37188, 37204, 37220, 37236, 37267, 37283, 37299, 37315, 37331, 37347, 37363, 37379, 37395, 37411, 37427, 37443, 37459, 37475, 37491, 37507, 37524, 37540, 37556, 37572, 37589, 37606, 37622, 37639, 37655, 37671, 37687, 37704, 37721, 37752, 37768, 37783, 37799, 37816, 37833, 37849, 37865, 37882, 37898, 37914, 37931, 37947, 37963, 37979, 37995, 38011, 38027, 38043, 38059, 38075, 38091, 38122, 38169, 38202, 38218, 38235, 38252, 38269, 38302, 38319, 38336, 38369, 38402, 38434, 38466, 39051, 39082, 39099, 39553, 39628, 39644, 40219, 40574, 40634, 40663, 40694, 41442, 42148, 42235, 42350, 42379, 42394, 42423, 42438, 42466, 42537, ...], ('GNV', 'SUDESTE'): [35900, 35901, 35902, 35903, 35915, 35916, 35917, 35918, 35930, 35931, 35932, 35933, 35945, 35946, 35947, 35948, 35960, 35961, 35962, 35963, 35975, 35976, 35977, 35978, 35990, 35991, 35992, 35993, 36005, 36006, 36007, 36008, 36020, 36021, 36022, 36023, 36035, 36036, 36037, 36038, 36050, 36051, 36052, 36053, 36065, 36066, 36067, 36068, 36080, 36081, 36082, 36083, 36095, 36096, 36097, 36098, 36110, 36111, 36112, 36113, 36125, 36126, 36127, 36128, 36140, 36141, 36142, 36143, 36155, 36156, 36157, 36158, 36170, 36171, 36172, 36173, 36185, 36186, 36187, 36188, 36200, 36201, 36202, 36203, 36215, 36216, 36217, 36218, 36230, 36231, 36232, 36233, 36245, 36246, 36247, 36248, 36260, 36261, 36262, 36263, ...], ('GNV', 'SUL'): [35904, 35905, 35906, 35919, 35920, 35921, 35934, 35935, 35936, 35949, 35950, 35951, 35964, 35965, 35966, 35979, 35980, 35981, 35994, 35995, 35996, 36009, 36010, 36011, 36024, 36025, 36026, 36039, 36040, 36041, 36054, 36055, 36056, 36069, 36070, 36071, 36084, 36085, 36086, 36099, 36100, 36101, 36114, 36115, 36116, 36129, 36130, 36131, 36144, 36145, 36146, 36159, 36160, 36161, 36174, 36175, 36176, 36189, 36190, 36191, 36204, 36205, 36206, 36219, 36220, 36221, 36234, 36235, 36236, 36249, 36250, 36251, 36264, 36265, 36266, 36280, 36281, 36282, 36295, 36296, 36297, 36310, 36311, 36312, 36326, 36327, 36328, 36342, 36343, 36344, 36357, 36358, 36359, 36372, 36373, 36374, 36387, 36388, 36389, 36402, ...], ('ÓLEO DIESEL', 'CENTRO OESTE'): [42612, 42613, 42614, 42615, 42639, 42640, 42641, 42642, 42666, 42667, 42668, 42669, 42693, 42694, 42695, 42696, 42720, 42721, 42722, 42723, 42747, 42748, 42749, 42750, 42774, 42775, 42776, 42777, 42801, 42802, 42803, 42804, 42828, 42829, 42830, 42831, 42855, 42856, 42857, 42858, 42882, 42883, 42884, 42885, 42909, 42910, 42911, 42912, 42936, 42937, 42938, 42939, 42963, 42964, 42965, 42966, 42990, 42991, 42992, 42993, 43017, 43018, 43019, 43020, 43044, 43045, 43046, 43047, 43071, 43072, 43073, 43074, 43098, 43099, 43100, 43101, 43125, 43126, 43127, 43128, 43152, 43153, 43154, 43155, 43179, 43180, 43181, 43182, 43206, 43207, 43208, 43209, 43233, 43234, 43235, 43236, 43260, 43261, 43262, 43263, ...], ('ÓLEO DIESEL', 'NORDESTE'): [42616, 42617, 42618, 42619, 42620, 42621, 42622, 42623, 42624, 42643, 42644, 42645, 42646, 42647, 42648, 42649, 42650, 42651, 42670, 42671, 42672, 42673, 42674, 42675, 42676, 42677, 42678, 42697, 42698, 42699, 42700, 42701, 42702, 42703, 42704, 42705, 42724, 42725, 42726, 42727, 42728, 42729, 42730, 42731, 42732, 42751, 42752, 42753, 42754, 42755, 42756, 42757, 42758, 42759, 42778, 42779, 42780, 42781, 42782, 42783, 42784, 42785, 42786, 42805, 42806, 42807, 42808, 42809, 42810, 42811, 42812, 42813, 42832, 42833, 42834, 42835, 42836, 42837, 42838, 42839, 42840, 42859, 42860, 42861, 42862, 42863, 42864, 42865, 42866, 42867, 42886, 42887, 42888, 42889, 42890, 42891, 42892, 42893, 42894, 42913, ...], ('ÓLEO DIESEL', 'NORTE'): [42625, 42626, 42627, 42628, 42629, 42630, 42631, 42652, 42653, 42654, 42655, 42656, 42657, 42658, 42679, 42680, 42681, 42682, 42683, 42684, 42685, 42706, 42707, 42708, 42709, 42710, 42711, 42712, 42733, 42734, 42735, 42736, 42737, 42738, 42739, 42760, 42761, 42762, 42763, 42764, 42765, 42766, 42787, 42788, 42789, 42790, 42791, 42792, 42793, 42814, 42815, 42816, 42817, 42818, 42819, 42820, 42841, 42842, 42843, 42844, 42845, 42846, 42847, 42868, 42869, 42870, 42871, 42872, 42873, 42874, 42895, 42896, 42897, 42898, 42899, 42900, 42901, 42922, 42923, 42924, 42925, 42926, 42927, 42928, 42949, 42950, 42951, 42952, 42953, 42954, 42955, 42976, 42977, 42978, 42979, 42980, 42981, 42982, 43003, 43004, ...], ('ÓLEO DIESEL', 'SUDESTE'): [42632, 42633, 42634, 42635, 42659, 42660, 42661, 42662, 42686, 42687, 42688, 42689, 42713, 42714, 42715, 42716, 42740, 42741, 42742, 42743, 42767, 42768, 42769, 42770, 42794, 42795, 42796, 42797, 42821, 42822, 42823, 42824, 42848, 42849, 42850, 42851, 42875, 42876, 42877, 42878, 42902, 42903, 42904, 42905, 42929, 42930, 42931, 42932, 42956, 42957, 42958, 42959, 42983, 42984, 42985, 42986, 43010, 43011, 43012, 43013, 43037, 43038, 43039, 43040, 43064, 43065, 43066, 43067, 43091, 43092, 43093, 43094, 43118, 43119, 43120, 43121, 43145, 43146, 43147, 43148, 43172, 43173, 43174, 43175, 43199, 43200, 43201, 43202, 43226, 43227, 43228, 43229, 43253, 43254, 43255, 43256, 43280, 43281, 43282, 43283, ...], ('ÓLEO DIESEL', 'SUL'): [42636, 42637, 42638, 42663, 42664, 42665, 42690, 42691, 42692, 42717, 42718, 42719, 42744, 42745, 42746, 42771, 42772, 42773, 42798, 42799, 42800, 42825, 42826, 42827, 42852, 42853, 42854, 42879, 42880, 42881, 42906, 42907, 42908, 42933, 42934, 42935, 42960, 42961, 42962, 42987, 42988, 42989, 43014, 43015, 43016, 43041, 43042, 43043, 43068, 43069, 43070, 43095, 43096, 43097, 43122, 43123, 43124, 43149, 43150, 43151, 43176, 43177, 43178, 43203, 43204, 43205, 43230, 43231, 43232, 43257, 43258, 43259, 43284, 43285, 43286, 43311, 43312, 43313, 43338, 43339, 43340, 43365, 43366, 43367, 43392, 43393, 43394, 43419, 43420, 43421, 43446, 43447, 43448, 43473, 43474, 43475, 43500, 43501, 43502, 43527, ...], ('ÓLEO DIESEL S10', 'CENTRO OESTE'): [54834, 54835, 54973, 54975, 54976, 55117, 55119, 55120, 55260, 55262, 55264, 55265, 55405, 55407, 55408, 55549, 55551, 55552, 55692, 55694, 55695, 55835, 55837, 55838, 55981, 55983, 55984, 56128, 56130, 56131, 56276, 56278, 56279, 56421, 56423, 56424, 56566, 56568, 56569, 56711, 56713, 56714, 56854, 56856, 56858, 56859, 57002, 57004, 57006, 57007, 57148, 57150, 57152, 57153, 57293, 57295, 57297, 57298, 57440, 57442, 57444, 57445, 57586, 57588, 57590, 57591, 57732, 57734, 57736, 57737, 57879, 57881, 57883, 57884, 58027, 58029, 58030, 58174, 58176, 58177, 58317, 58319, 58320, 58461, 58463, 58464, 58607, 58609, 58610, 58750, 58752, 58753, 58894, 58896, 58897, 59040, 59042, 59043, 59184, 59186, ...], ('ÓLEO DIESEL S10', 'NORDESTE'): [54702, 54703, 54706, 54707, 54829, 54831, 54832, 54833, 54839, 54840, 54842, 54847, 54968, 54970, 54971, 54974, 54979, 54981, 54982, 54984, 54989, 55112, 55114, 55115, 55118, 55123, 55125, 55126, 55128, 55133, 55256, 55258, 55259, 55263, 55268, 55270, 55271, 55273, 55278, 55400, 55402, 55403, 55406, 55411, 55413, 55414, 55416, 55421, 55544, 55546, 55547, 55550, 55555, 55557, 55558, 55560, 55565, 55687, 55689, 55690, 55693, 55698, 55700, 55701, 55703, 55708, 55830, 55832, 55833, 55836, 55841, 55843, 55844, 55846, 55852, 55976, 55978, 55979, 55982, 55987, 55989, 55990, 55992, 55998, 56122, 56125, 56126, 56129, 56134, 56136, 56137, 56139, 56145, 56270, 56273, 56274, 56277, 56282, 56284, 56285, ...], ('ÓLEO DIESEL S10', 'NORTE'): [54705, 54709, 54830, 54837, 54844, 54969, 54978, 54986, 55111, 55113, 55122, 55130, 55257, 55267, 55275, 55399, 55401, 55410, 55418, 55422, 55543, 55545, 55554, 55562, 55566, 55686, 55688, 55697, 55705, 55709, 55829, 55831, 55840, 55848, 55849, 55853, 55975, 55977, 55986, 55994, 55995, 55999, 56121, 56123, 56124, 56133, 56141, 56142, 56146, 56269, 56271, 56272, 56281, 56289, 56290, 56294, 56414, 56416, 56417, 56426, 56434, 56435, 56439, 56559, 56561, 56562, 56571, 56579, 56580, 56584, 56704, 56706, 56707, 56716, 56724, 56725, 56729, 56848, 56850, 56851, 56861, 56869, 56870, 56874, 56996, 56998, 56999, 57009, 57017, 57018, 57022, 57142, 57144, 57145, 57155, 57163, 57164, 57168, 57287, 57289, ...], ('ÓLEO DIESEL S10', 'SUDESTE'): [54704, 54711, 54836, 54841, 54846, 54972, 54977, 54983, 54988, 55116, 55121, 55127, 55132, 55261, 55266, 55272, 55277, 55404, 55409, 55415, 55420, 55548, 55553, 55559, 55564, 55691, 55696, 55702, 55707, 55834, 55839, 55845, 55851, 55980, 55985, 55991, 55997, 56127, 56132, 56138, 56144, 56275, 56280, 56286, 56292, 56420, 56425, 56431, 56437, 56565, 56570, 56576, 56582, 56710, 56715, 56721, 56727, 56855, 56860, 56866, 56872, 57003, 57008, 57014, 57020, 57149, 57154, 57160, 57166, 57294, 57299, 57305, 57311, 57441, 57

In [8]:
resultado = grupo['NÚMERO DE POSTOS PESQUISADOS'].sum().to_frame()
resultado

                               NÚMERO DE POSTOS PESQUISADOS
PRODUTO          REGIÃO
ETANOL HIDRATADO CENTRO OESTE                        472434
                 NORDESTE                           1061049
                 NORTE                               242562
                 SUDESTE                            3190178
                 SUL                                1052410
GASOLINA COMUM   CENTRO OESTE                        474131
                 NORDESTE                           1200306
                 NORTE                               415673
                 SUDESTE                            3233991
                 SUL                                1143045
GLP              CENTRO OESTE                        614634
                 NORDESTE                            797187
                 NORTE                               478249
                 SUDESTE                            2328664
                 SUL                                1120132
GNV              CENTRO OESTE                          3119
                 NORDESTE                             89006
                 NORTE                                  319
                 SUDESTE                             228315
                 SUL                                  39199
ÓLEO DIESEL      CENTRO OESTE                        405460
                 NORDESTE                            944479
                 NORTE                               365819
                 SUDESTE                            2385189
                 SUL                                 843649
ÓLEO DIESEL S10  CENTRO OESTE                         81659
                 NORDESTE                            258837
                 NORTE                                86042
                 SUDESTE                             512587
                 SUL                                 212772

## 7.2 Como os preços da Gasolina Comum em São Paulo variaram em 2018?

In [17]:
df_sp = df.query('ESTADO == "SAO PAULO"')
df_sp_gasolina = df_sp.query('PRODUTO == "GASOLINA COMUM"')
df_sp_gasolina_2018 = df_sp_gasolina.query('ANO == 2018')
df_sp_gasolina_2018.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
92319,2018-01-07,2018-01-13,SUDESTE,SAO PAULO,GASOLINA COMUM,1641,R$/l,3.988,0.156,3.499,4.599,0.411,0.039,3.577,0.104,2.990,3.9510,0.029,1,2018
92465,2018-01-14,2018-01-20,SUDESTE,SAO PAULO,GASOLINA COMUM,1648,R$/l,4.002,0.155,3.549,4.499,0.412,0.039,3.590,0.102,2.990,3.9014,0.028,1,2018
92610,2018-01-21,2018-01-27,SUDESTE,SAO PAULO,GASOLINA COMUM,1648,R$/l,4.006,0.160,3.499,4.899,0.410,0.040,3.596,0.102,2.990,3.9014,0.028,1,2018
92755,2018-01-28,2018-02-03,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.019,0.156,3.579,4.699,0.423,0.039,3.596,0.107,2.924,3.9537,0.030,1,2018
92901,2018-02-04,2018-02-10,SUDESTE,SAO PAULO,GASOLINA COMUM,1646,R$/l,4.004,0.157,3.579,4.597,0.416,0.039,3.588,0.102,2.990,3.9537,0.028,2,2018

## Estatísticas Descritivas

In [20]:
df_sp_gasolina_2018.describe()

,NÚMERO DE POSTOS PESQUISADOS,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
count,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.00000,52.000000,52.000000,52.000000,52.0
mean,1610.211538,4.202769,0.175500,3.671500,4.975750,0.442481,0.041750,3.760288,0.109654,3.31295,4.139454,0.029096,6.615385,2018.0
std,213.627432,0.180672,0.017955,0.163808,0.211198,0.063271,0.003965,0.163664,0.010712,0.26684,0.195897,0.002460,3.470627,0.0
min,102.000000,3.970000,0.150000,3.369000,4.499000,0.366000,0.034000,3.563000,0.087000,2.92400,3.887500,0.023000,1.000000,2018.0
25%,1639.000000,4.008000,0.159750,3.499000,4.899000,0.404500,0.039000,3.620250,0.102000,2.99000,3.965775,0.028000,4.000000,2018.0
50%,1642.000000,4.202000,0.173000,3.679000,4.999000,0.421500,0.040000,3.756500,0.108000,3.35000,4.095500,0.029000,7.000000,2018.0
75%,1644.000000,4.336250,0.189000,3.784000,5.099000,0.470250,0.044000,3.862250,0.116250,3.53250,4.259000,0.030000,9.250000,2018.0
max,1649.000000,4.512000,0.216000,3.969000,5.299000,0.640000,0.051000,4.085000,0.144000,3.76000,4.551000,0.037000,12.000000,2018.0

In [22]:
df_sp_gasolina_2018['PREÇO MÉDIO REVENDA'].describe().to_frame()

       PREÇO MÉDIO REVENDA
count            52.000000
mean              4.202769
std               0.180672
min               3.970000
25%               4.008000
50%               4.202000
75%               4.336250
max               4.512000

## 7.3 Como os preços da Gasolina Comum e do Etanol em São Paulo variaram em 2018?

In [26]:
df.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133,5,2004
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115,5,2004
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098,5,2004
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,5,2004
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,1.400,0.240,0.066,0.941,0.077,0.7441,1.03170,0.082,5,2004

In [53]:
df2_sp = df.query('ESTADO == "SAO PAULO"')
df2_sp_gasolina_e_etanol = df2_sp.query('PRODUTO == "GASOLINA COMUM" or PRODUTO == "ETANOL HIDRATADO"')
df2_sp_gasolina_e_etanol_2018 = df2_sp_gasolina_e_etanol.query('ANO == 2018')
df2_sp_gasolina_e_etanol_2018.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
92238,2018-01-07,2018-01-13,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1664,R$/l,2.833,0.139,2.449,3.399,0.338,0.049,2.495,0.092,2.1842,2.8833,0.037,1,2018
92319,2018-01-07,2018-01-13,SUDESTE,SAO PAULO,GASOLINA COMUM,1641,R$/l,3.988,0.156,3.499,4.599,0.411,0.039,3.577,0.104,2.9900,3.9510,0.029,1,2018
92384,2018-01-14,2018-01-20,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1661,R$/l,2.868,0.134,2.399,3.399,0.331,0.047,2.537,0.087,2.2600,2.8471,0.034,1,2018
92465,2018-01-14,2018-01-20,SUDESTE,SAO PAULO,GASOLINA COMUM,1648,R$/l,4.002,0.155,3.549,4.499,0.412,0.039,3.590,0.102,2.9900,3.9014,0.028,1,2018
92529,2018-01-21,2018-01-27,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1662,R$/l,2.874,0.135,2.399,3.399,0.324,0.047,2.550,0.095,1.6900,2.9722,0.037,1,2018

In [54]:
df2_sp_gasolina_e_etanol_2018.shape

(104, 20)

In [55]:
df2_sp_gasolina_e_etanol_2018.describe()

,NÚMERO DE POSTOS PESQUISADOS,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
count,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.0
mean,1620.557692,3.457337,0.167760,2.958663,4.318058,0.397048,0.050663,3.060288,0.108510,2.639623,3.462438,0.037481,6.615385,2018.0
std,213.422086,0.766239,0.021546,0.736680,0.681788,0.070977,0.012328,0.721584,0.013409,0.711083,0.707791,0.010599,3.453738,0.0
min,102.000000,2.393000,0.133000,1.895000,3.199000,0.291000,0.034000,2.042000,0.086000,1.674400,2.416900,0.023000,1.000000,2018.0
25%,1641.000000,2.726000,0.150750,2.259000,3.699000,0.336750,0.040000,2.364250,0.099750,1.917400,2.790875,0.029000,4.000000,2018.0
50%,1647.000000,3.431000,0.165000,2.919000,4.244500,0.393000,0.048500,3.076000,0.107000,2.599500,3.517350,0.034000,7.000000,2018.0
75%,1662.000000,4.199000,0.186250,3.679000,4.999000,0.426250,0.055250,3.751750,0.116250,3.350000,4.092750,0.043250,9.250000,2018.0
max,1665.000000,4.512000,0.216000,3.969000,5.299000,0.640000,0.086000,4.085000,0.150000,3.760000,4.551000,0.066000,12.000000,2018.0

In [56]:
df2_sp_gasolina_e_etanol_2018[['PREÇO MÉDIO REVENDA', 'PREÇO MÍNIMO REVENDA', 'PREÇO MÁXIMO REVENDA']].describe()

       PREÇO MÉDIO REVENDA  PREÇO MÍNIMO REVENDA  PREÇO MÁXIMO REVENDA
count           104.000000            104.000000            104.000000
mean              3.457337              2.958663              4.318058
std               0.766239              0.736680              0.681788
min               2.393000              1.895000              3.199000
25%               2.726000              2.259000              3.699000
50%               3.431000              2.919000              4.244500
75%               4.199000              3.679000              4.999000
max               4.512000              3.969000              5.299000

Outra forma de fazer:

In [58]:
resultado = df.query('(PRODUTO == "GASOLINA COMUM" or PRODUTO == "ETANOL HIDRATADO") and ESTADO == "SAO PAULO" and ANO == 2018')

# 2° forma (com lista)
resultado = df.query('(PRODUTO in ["GASOLINA COMUM", "ETANOL HIDRATADO"]) and ESTADO == "SAO PAULO" and ANO == 2018')

In [59]:
resultado.shape

(104, 20)

In [60]:
resultado.describe()

,NÚMERO DE POSTOS PESQUISADOS,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
count,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.0
mean,1620.557692,3.457337,0.167760,2.958663,4.318058,0.397048,0.050663,3.060288,0.108510,2.639623,3.462438,0.037481,6.615385,2018.0
std,213.422086,0.766239,0.021546,0.736680,0.681788,0.070977,0.012328,0.721584,0.013409,0.711083,0.707791,0.010599,3.453738,0.0
min,102.000000,2.393000,0.133000,1.895000,3.199000,0.291000,0.034000,2.042000,0.086000,1.674400,2.416900,0.023000,1.000000,2018.0
25%,1641.000000,2.726000,0.150750,2.259000,3.699000,0.336750,0.040000,2.364250,0.099750,1.917400,2.790875,0.029000,4.000000,2018.0
50%,1647.000000,3.431000,0.165000,2.919000,4.244500,0.393000,0.048500,3.076000,0.107000,2.599500,3.517350,0.034000,7.000000,2018.0
75%,1662.000000,4.199000,0.186250,3.679000,4.999000,0.426250,0.055250,3.751750,0.116250,3.350000,4.092750,0.043250,9.250000,2018.0
max,1665.000000,4.512000,0.216000,3.969000,5.299000,0.640000,0.086000,4.085000,0.150000,3.760000,4.551000,0.066000,12.000000,2018.0

In [61]:
resultado[['PREÇO MÉDIO REVENDA', 'PREÇO MÍNIMO REVENDA', 'PREÇO MÁXIMO REVENDA']].describe()

       PREÇO MÉDIO REVENDA  PREÇO MÍNIMO REVENDA  PREÇO MÁXIMO REVENDA
count           104.000000            104.000000            104.000000
mean              3.457337              2.958663              4.318058
std               0.766239              0.736680              0.681788
min               2.393000              1.895000              3.199000
25%               2.726000              2.259000              3.699000
50%               3.431000              2.919000              4.244500
75%               4.199000              3.679000              4.999000
max               4.512000              3.969000              5.299000

In [64]:
resultado.groupby('PRODUTO')['PREÇO MÉDIO REVENDA'].describe()

,count,mean,std,min,25%,50%,75%,max
PRODUTO,,,,,,,,
ETANOL HIDRATADO,52.0,2.711904,0.141365,2.393,2.6315,2.720,2.83825,2.892
GASOLINA COMUM,52.0,4.202769,0.180672,3.970,4.0080,4.202,4.33625,4.512